### PR TITLE
AudioEngine BGM init, + minor changes

### PR DESCRIPTION
**Pull request by SkyVelleity**
All my work to add a small audio scheduler in, dynamic gameplay-based background music, as well as a few bespoke loops the engine can seamlessly switch between as gameplay demands. Most enjoyable once merged with dev and it can take on a few other key changes :^)

### CODE REVIEW

**Comment by NoahPJac** [comment]
Looks great to me

**Comment by SkyVelleity** [comment]
Aww why you close (͒˃̩̩⌂˂̩̩ ͒)

**Comment by SkyVelleity** [comment]
You're supposed to click review, then approve

**Review by Matthew-Gilbert — APPROVED** [review]
*closes your pr* nothing personel kid

**Pull request merged**
